on: push
jobs:
    job1:
      steps:
      - uses: https://eoelab.org:1027/actions/checkout@v4
      - run: sudo apt install python3-pip
      - run: pip install torch torchvision tqdm
      
      
      - run: python3 ./main.py 